"use strict";

const FIRST_GENERATION_BLUEPRINT = Object.freeze([
  { gate_number:1, gate_key:"attention", name:"Attention", chapter_title:"Gate 1: Attention", core_lesson:"Attention is trained through gentle return.", child_learning_statement:"I can return my attention when it wanders.", reflection_questions:["When does your child return attention with the least support?"], journal_prompts:["Describe one moment your child returned to focus today."], developing_signs:["Short bursts of focus with reminders."], integration_signs:["Returns to task with fewer prompts."], ceremony:"Focus lantern lighting and one sentence commitment.", parent_guidance:"Use short intervals and celebrate return, not perfection.", do_not_guidance:"Do not shame distraction; treat it as a practice moment." },
  { gate_number:2, gate_key:"emotion", name:"Emotion", chapter_title:"Gate 2: Emotion", core_lesson:"Emotions are signals that can be named and softened.", child_learning_statement:"I can notice big feelings and find my way back.", reflection_questions:["What helps emotions soften in your home?"], journal_prompts:["Draw your emotional weather and what changed it."], developing_signs:["Names feelings after support."], integration_signs:["Recovers from big feelings with familiar tools."], ceremony:"Emotional awareness stone: choose a stone that represents calm return.", parent_guidance:"Co-regulate first, then discuss choices.", warning_language:"Parent observation only, not diagnosis." },
  { gate_number:3, gate_key:"choice", name:"Choice", chapter_title:"Gate 3: Choice", core_lesson:"Choice builds agency when paired with consequence.", child_learning_statement:"I can make a helpful choice and repair when I miss.", reflection_questions:["Which choices does your child now make without prompting?"], journal_prompts:["Write about one hard choice and its outcome."], developing_signs:["Pauses before acting in some routines."], integration_signs:["Names options and picks a constructive one."], ceremony:"Two-path ritual with family witness.", parent_guidance:"Offer bounded choices and follow through consistently." },
  { gate_number:4, gate_key:"body", name:"Body", chapter_title:"Gate 4: Body", core_lesson:"The body is a doorway to regulation and readiness.", child_learning_statement:"I can notice my body and reset it for learning.", reflection_questions:["What body cues show your child needs a reset?"], journal_prompts:["What movement helped today?"], developing_signs:["Benefits from movement or breathing cues."], integration_signs:["Initiates a body reset independently."], ceremony:"Body wisdom stretch circle.", parent_guidance:"Normalize movement breaks before overload." },
  { gate_number:5, gate_key:"discipline", name:"Discipline", chapter_title:"Gate 5: Discipline", core_lesson:"Discipline is steady practice, not punishment.", child_learning_statement:"I can keep going with structure and support.", reflection_questions:["What routine helps effort become reliable?"], journal_prompts:["Track one routine for seven days."], developing_signs:["Completes routines with reminders."], integration_signs:["Sustains routines with predictable cues."], ceremony:"Routine ribbon ceremony.", parent_guidance:"Use rhythm, cue, repeat, celebrate." },
  { gate_number:6, gate_key:"truth", name:"Truth", chapter_title:"Gate 6: Truth", core_lesson:"Truth builds trust and inner alignment.", child_learning_statement:"I can tell the truth even when it is hard.", reflection_questions:["How do you respond when truth is difficult?"], journal_prompts:["Write a time honesty repaired trust."], developing_signs:["Admits mistakes with support."], integration_signs:["Offers truthful account without heavy prompting."], ceremony:"Truth candle and spoken commitment.", parent_guidance:"Reward honesty with safety and accountability." },
  { gate_number:7, gate_key:"repair", name:"Repair", chapter_title:"Gate 7: Repair", core_lesson:"Relationships grow through repair after rupture.", child_learning_statement:"I can repair after I hurt someone.", reflection_questions:["What repair language is becoming natural?"], journal_prompts:["Describe a rupture-repair moment this week."], developing_signs:["Needs coaching to apologize and restore."], integration_signs:["Initiates apology and corrective action."], ceremony:"Bridge-building ceremony with shared statement.", parent_guidance:"Teach repair steps explicitly and rehearse." },
  { gate_number:8, gate_key:"creation", name:"Creation", chapter_title:"Gate 8: Creation", core_lesson:"Creation turns imagination into contribution.", child_learning_statement:"I can make something meaningful and share it.", reflection_questions:["Where does your child show original problem-solving?"], journal_prompts:["Document one thing your child created and why it mattered."], developing_signs:["Experiments when invited."], integration_signs:["Starts and completes simple creative projects."], ceremony:"Creation showcase circle.", parent_guidance:"Value process, iteration, and expression." },
  { gate_number:9, gate_key:"community", name:"Community", chapter_title:"Gate 9: Community", core_lesson:"Belonging grows through contribution and care.", child_learning_statement:"I can help my group and receive help too.", reflection_questions:["How does your child contribute to family life?"], journal_prompts:["Name one act of contribution observed this week."], developing_signs:["Participates when invited."], integration_signs:["Initiates helpful contribution."], ceremony:"Community gratitude round.", parent_guidance:"Create small family roles with visible value." },
  { gate_number:10, gate_key:"legacy", name:"Legacy", chapter_title:"Gate 10: Legacy", core_lesson:"Legacy is daily character repeated over time.", child_learning_statement:"I can practice who I want to become.", reflection_questions:["What value is your child carrying forward consistently?"], journal_prompts:["Write a letter from your future self about this season."], developing_signs:["Can name admired values."], integration_signs:["Acts in line with chosen values across settings."], ceremony:"Legacy vow and family blessing.", parent_guidance:"Name values in action and revisit often." }
]);

const BLUEPRINT_BY_KEY = Object.freeze(new Map(FIRST_GENERATION_BLUEPRINT.map((g) => [g.gate_key, g])));
module.exports = { FIRST_GENERATION_BLUEPRINT, BLUEPRINT_BY_KEY };
