"use strict";

const GATES_HABIT_BANK = [
  { gate_number:1, gate_key:"attention", name:"Attention", habit_markers:["returns to task after distraction","listens without interrupting briefly","notices when attention drifts","completes a short focus ritual"], integration_signals:["growth signal: can refocus without repeated reminders","integration signal: sustains attention through a full short task","integration signal: notices and names distractions before restarting"], self_correction_signals:["self-correction: pauses and resets attention after drifting","self-correction: asks for a focus reset when overwhelmed"], family_practices:["family practice: 5-minute shared focus block","family practice: naming one distraction and one reset strategy"], parent_mirror_prompts:["Where am I modeling focused presence and where am I fragmenting attention?"], identity_statements:["I can notice my attention and bring it back with care."] },
  { gate_number:2, gate_key:"emotion", name:"Emotion", habit_markers:["names feelings","asks for space","breathes before reacting","recovers faster after overwhelm"], integration_signals:["growth signal: names emotions before escalation","integration signal: returns to connection after hard feelings","integration signal: uses a calming practice without prompting"], self_correction_signals:["self-correction: notices intensity rising and asks for pause","self-correction: restarts conversation after regulating"], family_practices:["family practice: daily feelings check-in","family practice: shared breathing reset before problem-solving"], parent_mirror_prompts:["How do I show my child that strong feelings can be felt and guided?"], identity_statements:["My feelings matter, and I can move through them wisely."] },
  { gate_number:3, gate_key:"choice", name:"Choice", habit_markers:["pauses before acting","accepts consequences","chooses a helpful action","notices repeated patterns"], integration_signals:["growth signal: considers options before deciding","integration signal: owns choices without blame shifting","integration signal: interrupts an unhelpful emerging pattern"], self_correction_signals:["self-correction: revises a choice after reflection","self-correction: names a better next action after misstep"], family_practices:["family practice: two-option pause before key decisions","family practice: evening reflection on one choice and one learning"], parent_mirror_prompts:["Where can I slow down and model intentional choice-making today?"], identity_statements:["I can choose actions that align with who I am becoming."] },
  { gate_number:4, gate_key:"body", name:"Body", habit_markers:["notices hunger/tiredness","follows rest routines","moves body to regulate","cares for physical space"], integration_signals:["growth signal: links body state to behavior","integration signal: uses movement, food, or rest to reset","integration signal: maintains simple body-care rhythms"], self_correction_signals:["self-correction: asks for water, food, or rest before shutdown","self-correction: re-enters activity after body regulation"], family_practices:["family practice: body-state check before transitions","family practice: shared movement reset between tasks"], parent_mirror_prompts:["What is my body signaling, and how am I honoring it in front of my child?"], identity_statements:["My body gives me wisdom, and I can respond to it."] },
  { gate_number:5, gate_key:"discipline", name:"Discipline", habit_markers:["makes bed","returns after quitting","completes morning routine","practices without immediate reward"], integration_signals:["growth signal: returns to effort after discomfort","integration signal: follows through on small daily commitments","integration signal: builds consistency across days"], self_correction_signals:["self-correction: takes a short break and resumes practice","self-correction: asks for structure, then completes the next step"], family_practices:["family practice: morning rhythm board","family practice: celebrate consistency over intensity"], parent_mirror_prompts:["How am I showing steady commitment when motivation is low?"], identity_statements:["I can keep showing up, even when it is hard."] },
  { gate_number:6, gate_key:"truth", name:"Truth", habit_markers:["admits mistakes","shares hidden feelings","accepts correction","tells truth without being forced"], integration_signals:["growth signal: speaks honestly with less defensiveness","integration signal: names inner experience with clarity","integration signal: repairs trust through truthful action"], self_correction_signals:["self-correction: corrects a story after reflection","self-correction: returns to share truth after initial avoidance"], family_practices:["family practice: truth circle with one honest share each","family practice: normalize saying 'I was wrong'"], parent_mirror_prompts:["Where can I practice honest ownership so truth feels safe in our home?"], identity_statements:["I can tell the truth and stay connected."] },
  { gate_number:7, gate_key:"repair", name:"Repair", habit_markers:["apologizes","makes amends","notices impact","rejoins after conflict"], integration_signals:["growth signal: recognizes harm sooner","integration signal: follows apology with restorative action","integration signal: reconnects after conflict with openness"], self_correction_signals:["self-correction: initiates repair without waiting to be told","self-correction: asks what would help restore trust"], family_practices:["family practice: conflict reset ritual","family practice: name impact and one repair step"], parent_mirror_prompts:["How am I modeling repair as strength rather than shame?"], identity_statements:["When I hurt someone, I can repair and rebuild trust."] },
  { gate_number:8, gate_key:"creation", name:"Creation", habit_markers:["starts a meaningful project","finishes a small creation","contributes beauty/order","solves problems creatively"], integration_signals:["growth signal: initiates creative effort regularly","integration signal: completes and shares creations","integration signal: uses imagination to solve real problems"], self_correction_signals:["self-correction: revises work after feedback","self-correction: restarts a stalled project with a smaller step"], family_practices:["family practice: weekly create-and-share hour","family practice: family space improvement project"], parent_mirror_prompts:["What am I creating that shows my child how to turn ideas into contribution?"], identity_statements:["I can create value, beauty, and solutions."] },
  { gate_number:9, gate_key:"community", name:"Community", habit_markers:["helps without prompting","cleans shared space","includes others","contributes to family rhythm"], integration_signals:["growth signal: notices shared needs in real time","integration signal: contributes reliably to group wellbeing","integration signal: welcomes others into participation"], self_correction_signals:["self-correction: re-engages after withdrawing from group rhythm","self-correction: offers support after noticing missed contribution"], family_practices:["family practice: daily shared-space reset","family practice: weekly contribution reflection"], parent_mirror_prompts:["How am I living as a contributor to our family rhythm today?"], identity_statements:["I belong, and I help my community thrive."] },
  { gate_number:10, gate_key:"legacy", name:"Legacy", habit_markers:["considers future impact","repeats helpful habits","teaches someone younger","makes choices with tomorrow in mind"], integration_signals:["growth signal: connects present action to future outcomes","integration signal: sustains helpful habits over time","integration signal: passes learning forward to others"], self_correction_signals:["self-correction: shifts a short-term choice toward long-term good","self-correction: renews a helpful habit after a lapse"], family_practices:["family practice: tomorrow-minded decision check","family practice: teach-back moments with younger siblings or peers"], parent_mirror_prompts:["What legacy am I shaping through today's repeated actions?"], identity_statements:["My choices today can bless tomorrow."] }
];

function getGateHabitByKey(gateKey) {
  return GATES_HABIT_BANK.find((gate) => gate.gate_key === String(gateKey || "").trim().toLowerCase()) || null;
}

module.exports = { GATES_HABIT_BANK, getGateHabitByKey };
