"use strict";

module.exports = [
  {
    code: "TD",
    canonicalName: "Trust Dependence",
    name: "Trust Anchor",
    slug: "trust-anchor",
    shortDescription: "Loyalty is anchored in perceived reliability and integrity.",
    description: "Retention pattern where confidence in consistency, competence, and transparency keeps customers committed over time.",
    coreTrait: "credibility reliance",
    coreEnergy: "assurance",
    coreDriver: "Loyalty is driven by perceived reliability, integrity, and confidence that promises will be kept.",
    scientificBasis: "Commitment-Trust Theory (Morgan & Hunt, 1994): trust is a core antecedent of commitment and durable relationship retention.",
    whenStrong: "Retention remains stable through minor service disruptions because trust buffers short-term dissatisfaction.",
    overrelianceRisk: "Trust inertia can delay reassessment, causing people to tolerate quality decline longer than they should.",
    underdevelopedRisk: "Low trust sensitivity increases vigilance and exit probability when uncertainty appears.",
    coreStrengths: ["Stability under mild volatility", "Long-term retention", "Lower reactive churn"],
    blindSpots: ["Slow reevaluation of fit", "Can discount emerging alternatives", "May over-credit past reliability"],
    retentionNeeds: ["Consistency in delivery", "Transparent communication", "Visible corrective action after failures"],
    churnTriggers: ["Broken promises", "Perceived inconsistency", "Trust-damaging opacity"],
    loyaltySignals: ["Repeat usage despite minor errors", "Low comparison behavior", "High tolerance for short-term noise"],
    balancedStateMeaning: "Trust and performance reinforce each other.",
    underexpressedMeaning: "Trust is weak and loyalty becomes unstable.",
    overexpressedMeaning: "Trust inertia may hide declining value.",
    stressPattern: "Trust breach creates rapid loyalty collapse.",
    rebalanceGuidance: "Rebuild proof quickly through transparent recovery actions.",
    imageKey: "loyalty-td",
    imageVariants: [],
  },
  {
    code: "SA",
    canonicalName: "Satisfaction Attachment",
    name: "Satisfaction Loyalist",
    slug: "satisfaction-loyalist",
    shortDescription: "Loyalty is sustained by consistent value and outcome quality.",
    description: "Retention pattern where repeat behavior is primarily reinforced by expected utility, performance, and satisfaction continuity.",
    coreTrait: "value reinforcement",
    coreEnergy: "stability",
    coreDriver: "Loyalty is driven by repeatedly meeting or exceeding expected value.",
    scientificBasis: "Satisfaction-Profit Chain and loyalty outcomes research (Fornell, 1992; Oliver, 1999) linking satisfaction to repeat retention.",
    whenStrong: "Customers renew when quality remains dependable and outcomes stay aligned with expectations.",
    overrelianceRisk: "Past satisfaction can mask current slippage and delay corrective action.",
    underdevelopedRisk: "Small performance drops quickly elevate churn intent and comparison shopping.",
    coreStrengths: ["Rational retention foundation", "Clear value-response loop", "Measurable service accountability"],
    blindSpots: ["Can underweight emotional signals", "May ignore trust erosion if utility seems acceptable", "Retention can be vulnerable to superior offers"],
    retentionNeeds: ["Consistent quality delivery", "Fast issue recovery", "Evidence of ongoing value improvement"],
    churnTriggers: ["Perceived value decline", "Unresolved service failures", "Better quality-price alternatives"],
    loyaltySignals: ["Renewal tied to outcomes", "Frequent value confirmation", "Retention after proven performance"],
    balancedStateMeaning: "High satisfaction supports steady repeat behavior.",
    underexpressedMeaning: "Value perception weakens and churn risk rises.",
    overexpressedMeaning: "Past satisfaction masks emerging alternatives.",
    stressPattern: "Value drop triggers comparison shopping.",
    rebalanceGuidance: "Close value gaps and prove improvements quickly.",
    imageKey: "loyalty-sa",
    imageVariants: [],
  },
  {
    code: "ECM",
    canonicalName: "Emotional Commitment",
    name: "Emotional Loyalist",
    slug: "emotional-loyalist",
    shortDescription: "Loyalty is rooted in emotional attachment and identity resonance.",
    description: "Retention pattern where belonging, affinity, and symbolic alignment amplify commitment beyond functional value alone.",
    coreTrait: "affective bond",
    coreEnergy: "attachment",
    coreDriver: "Loyalty is driven by emotional connection and identity-consistent affiliation.",
    scientificBasis: "Brand attachment and emotional bond literature (Thomson et al., 2005; Batra et al., 2012) linking affective attachment to persistence.",
    whenStrong: "Retention persists during moderate value fluctuations because relational meaning remains high.",
    overrelianceRisk: "Emotion can override objective fit and delay needed switching.",
    underdevelopedRisk: "Without emotional resonance, the relationship becomes purely transactional and easier to replace.",
    coreStrengths: ["Deep relational stickiness", "Advocacy potential", "Higher forgiveness when trust/value remain intact"],
    blindSpots: ["Can confuse familiarity with fit", "May under-detect utility decline", "Risk of symbolic attachment without structural value"],
    retentionNeeds: ["Authentic brand meaning", "Consistent identity signals", "Emotion backed by reliable delivery"],
    churnTriggers: ["Identity misalignment", "Emotional disengagement", "Perceived inauthentic behavior"],
    loyaltySignals: ["Affinity-based repeat behavior", "Advocacy language", "Continued engagement beyond transactions"],
    balancedStateMeaning: "Emotion amplifies loyalty while value remains visible.",
    underexpressedMeaning: "Relationship feels transactional and shallow.",
    overexpressedMeaning: "Emotional pull can outweigh rational fit.",
    stressPattern: "Emotional disengagement leads to silent churn risk.",
    rebalanceGuidance: "Reconnect story and meaning with credible value delivery.",
    imageKey: "loyalty-ecm",
    imageVariants: [],
  },
  {
    code: "CH",
    canonicalName: "Convenience Habit",
    name: "Habitual Loyalist",
    slug: "habitual-loyalist",
    shortDescription: "Loyalty persists through routine, ease, and low-friction repetition.",
    description: "Retention pattern where default choice architecture and repeated context cues produce automatic reuse.",
    coreTrait: "friction avoidance",
    coreEnergy: "efficiency",
    coreDriver: "Loyalty is driven by habit loops and convenience-based default behavior.",
    scientificBasis: "Habit and automaticity research (Verplanken & Aarts, 1999; Wood & Neal, 2009) showing repeated contextual cues sustain behavior.",
    whenStrong: "Retention remains high when usage stays easy and integrated into existing routines.",
    overrelianceRisk: "Habit can preserve retention even when quality falls, hiding emerging dissatisfaction.",
    underdevelopedRisk: "Without routine strength, switching becomes effortless under small disruptions.",
    coreStrengths: ["Low cognitive load retention", "High repeat probability", "Operational resilience through default behavior"],
    blindSpots: ["Can mask poor fit", "May reduce active re-evaluation", "Sensitive to competitor convenience gains"],
    retentionNeeds: ["Low-friction journeys", "Stable usage cues", "Seamless repeat workflows"],
    churnTriggers: ["Routine disruption", "Convenience loss", "Competitor offers lower effort pathways"],
    loyaltySignals: ["Automatic repurchase", "Low-decision repeat use", "Consistent behavior in similar contexts"],
    balancedStateMeaning: "Convenience supports retention without masking dissatisfaction.",
    underexpressedMeaning: "Routine is weak and switching becomes easy.",
    overexpressedMeaning: "Habit persists despite poor fit.",
    stressPattern: "Switching ease spikes churn when friction is reduced elsewhere.",
    rebalanceGuidance: "Sustain ease while strengthening trust and value foundations.",
    imageKey: "loyalty-ch",
    imageVariants: [],
  },
  {
    code: "SF",
    canonicalName: "Switching Friction",
    name: "Friction Loyalist",
    slug: "friction-loyalist",
    shortDescription: "Loyalty is retained through perceived switching costs and barriers.",
    description: "Retention pattern where procedural, financial, cognitive, or contractual switching costs reduce exit behavior.",
    coreTrait: "inertia leverage",
    coreEnergy: "retention lock",
    coreDriver: "Loyalty is driven by switching frictions that make alternatives costly in time, effort, or risk.",
    scientificBasis: "Switching cost theory (Klemperer, 1995; Burnham et al., 2003) showing barriers can sustain retention independent of affection.",
    whenStrong: "Retention remains high in the short term because switching feels costly or risky.",
    overrelianceRisk: "Lock-in dependence can suppress goodwill and increase backlash once alternatives become feasible.",
    underdevelopedRisk: "When friction is near zero, opportunistic switching can rise quickly.",
    coreStrengths: ["Protective retention buffer", "Reduces impulsive churn", "Buys time for value recovery"],
    blindSpots: ["Can overestimate true loyalty", "May hide low emotional commitment", "Risk of coerced retention perception"],
    retentionNeeds: ["Fair, transparent switching terms", "Value reinforcement beyond barriers", "Trust-based renewal signals"],
    churnTriggers: ["Perceived lock-in abuse", "Barrier removal by competitors", "Accumulated resentment"],
    loyaltySignals: ["Delayed switching despite alternatives", "Retention concentrated around contractual cycles", "Low referral despite continued usage"],
    balancedStateMeaning: "Barriers are fair and secondary to trust/value.",
    underexpressedMeaning: "No protective friction against opportunistic switching.",
    overexpressedMeaning: "Lock-in dominates and goodwill erodes.",
    stressPattern: "Perceived lock-in can trigger backlash and forced exits.",
    rebalanceGuidance: "Reduce coercive friction and earn renewal through value.",
    imageKey: "loyalty-sf",
    imageVariants: [],
  },
];
