'use strict';
const crypto=require('node:crypto');const project=require('../validation/projectChildFixture');const {evaluateFeaturePolicy}=require('./gatesV2FeaturePolicy');const {validateContext}=require('./gatesV2ServiceTypes');const {GatesV2ServiceError,safeServiceError}=require('./gatesV2ServiceErrors');
class GatesV2ExperienceService{
 constructor({persistence,clock=()=>new Date().toISOString(),id=()=>crypto.randomUUID(),contentFlag=()=> 'gates_emotion_k1_content_v1'}){this.persistence=persistence;this.clock=clock;this.id=id;this.contentFlag=contentFlag;}
 _context(ctx,specific){if(!validateContext(ctx))throw new GatesV2ServiceError('CHILD_OWNERSHIP_MISMATCH');const policy=evaluateFeaturePolicy(ctx.feature_flags,specific);if(!policy.enabled)throw new GatesV2ServiceError('FEATURE_DISABLED');return policy;}
 async _releaseExperience(release,id,version){const x=(release.manifest_json.experiences||[]).find(e=>e.experience_id===id&&(!version||e.experience_version===version));if(!x)throw new GatesV2ServiceError('EXPERIENCE_NOT_AVAILABLE');return x;}
 async listAvailableExperiences(ctx){try{this._context(ctx,this.contentFlag());const release=await this.persistence.releases.selectOfferedRelease();return (release.manifest_json.experiences||[]).map(x=>({release_id:release.release_id,experience_id:x.experience_id,experience_version:x.experience_version,gate_id:x.gate_id,age_band:x.age_band,locale:x.locale}));}catch(e){throw safeServiceError(e);}}
 async startExperienceSession(ctx,input){try{const flag=this.contentFlag(input);const policy=this._context(ctx,flag);const release=input.release_id?await this.persistence.releases.getForNewSession(input.release_id):await this.persistence.releases.selectOfferedRelease();const experience=await this._releaseExperience(release,input.experience_id,input.experience_version);const sessionId=this.id();await this.persistence.sessions.createSession({session_id:sessionId,parent_profile_id:ctx.parent_profile_id,child_id:ctx.child_id,gate_id:experience.gate_id,experience_id:experience.experience_id,release_id:release.release_id,experience_version:experience.experience_version,age_band:input.age_band||experience.age_band,locale:input.locale||experience.locale||'en-US',feature_variant_json:policy.variants,state_json:{session_id:sessionId,revision:0,status:'active',node_history:[]},created_at:this.clock()});return this.applyExperienceAction(ctx,{session_id:sessionId,expected_revision:0,idempotency_key:input.idempotency_key,action:{type:'START_EXPERIENCE'}});}catch(e){throw safeServiceError(e);}}
 async getExperienceSession(ctx,input){try{this._context(ctx,this.contentFlag(input));const session=await this.persistence.sessions.resumeSession({...input,parent_profile_id:ctx.parent_profile_id,child_id:ctx.child_id});const release=await this.persistence.releases.getPinned(session.release_id);const experience=await this._releaseExperience(release,session.experience_id,session.experience_version);const projected=project(experience,{...session.state_json,fixture_id:session.session_id});if(!projected.valid)throw new GatesV2ServiceError('INVALID_STORED_SESSION_STATE');return projected.projection;}catch(e){throw safeServiceError(e);}}
 async applyExperienceAction(ctx,input){try{this._context(ctx,this.contentFlag(input));const result=await this.persistence.transactions.transactionallyApplyAction({...input,parent_profile_id:ctx.parent_profile_id,child_id:ctx.child_id,occurred_at:input.occurred_at||this.clock()});return result.projection;}catch(e){throw safeServiceError(e);}}
 async resumeExperienceSession(ctx,input){return this.getExperienceSession(ctx,input);}
 async _setStatus(ctx,input,status){try{this._context(ctx,this.contentFlag(input));const result=await this.persistence.transactions.transactionallySetStatus({...input,parent_profile_id:ctx.parent_profile_id,child_id:ctx.child_id,occurred_at:input.occurred_at||this.clock()},status);return this.getExperienceSession(ctx,{session_id:result.session.session_id});}catch(e){throw safeServiceError(e);}}
 async pauseExperienceSession(ctx,input){return this._setStatus(ctx,input,'paused');}
 async abandonExperienceSession(ctx,input){return this._setStatus(ctx,input,'abandoned');}
 async replayExperienceSession(ctx,input){return this.applyExperienceAction(ctx,{...input,action:{type:'REPLAY'}});}
}
module.exports=GatesV2ExperienceService;
