'use strict';

const ACTION_TYPES = Object.freeze({
  START_EXPERIENCE: 'START_EXPERIENCE',
  VIEW_NODE: 'VIEW_NODE',
  SELECT_CHOICE: 'SELECT_CHOICE',
  COMPLETE_PRACTICE: 'COMPLETE_PRACTICE',
  COMPLETE_REFLECTION: 'COMPLETE_REFLECTION',
  REPLAY: 'REPLAY',
  RESTART: 'RESTART',
});

const ERROR_CODES = Object.freeze({
  INVALID_ACTION: 'INVALID_ACTION',
  INVALID_EXPERIENCE: 'INVALID_EXPERIENCE',
  INVALID_NODE: 'INVALID_NODE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  SESSION_COMPLETE: 'SESSION_COMPLETE',
  REPLAY_LIMIT_REACHED: 'REPLAY_LIMIT_REACHED',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
});

module.exports = { ACTION_TYPES, ERROR_CODES };
