"use strict";
const express = require("express");
const svc = require("./leaderWithinService");
function asyncRoute(fn){return (req,res)=>fn(req,res).catch(e=>res.status(e.status||500).json({error:e.message}));}
function html(title, body){return `<!doctype html><html><head><title>${title}</title><link rel="stylesheet" href="/the-leader-within/programs/program.css"></head><body><main class="section">${body}</main></body></html>`;}
function createLeaderWithinRouter(pool){
 const r=express.Router();
 r.get('/api/the-leader-within/my-program', asyncRoute(async(req,res)=>res.json(await svc.getYouthDashboard(pool,req))));
 r.post('/api/the-leader-within/my-program/practice', asyncRoute(async(req,res)=>res.json(await svc.selectPractice(pool,req))));
 r.post('/api/the-leader-within/my-program/reflections', asyncRoute(async(req,res)=>res.json(await svc.submitReflection(pool,req))));
 r.post('/api/the-leader-within/my-program/shared-perspective', asyncRoute(async(req,res)=>res.json(await svc.submitSharedPerspective(pool,req))));
 r.get('/api/admin/the-leader-within', asyncRoute(async(req,res)=>res.json(await svc.facilitatorDashboard(pool,req))));
 r.get('/api/admin/the-leader-within/participants/:participantId', asyncRoute(async(req,res)=>res.json(await svc.participantProfile(pool,req))));
 r.post('/api/admin/the-leader-within/participants/:participantId/notes', asyncRoute(async(req,res)=>res.json(await svc.addNote(pool,req))));
 r.post('/api/admin/the-leader-within/enrollments/:enrollmentId/session', asyncRoute(async(req,res)=>res.json(await svc.facilitatorControl(pool,req))));
 r.get('/the-leader-within/my-program', asyncRoute(async(req,res)=>{const d=await svc.getYouthDashboard(pool,req);res.type('html').send(html('The Leader Within', `<section class="hero"><h1>The Leader Within</h1><p>Welcome Back, ${d.participant.first_name}</p><p>${d.program.title}</p><p>Week ${d.current.week} of ${d.program.duration_weeks} • ${d.current.phase}</p><p>Today: Session ${d.current.session} — ${d.current.session_title}</p></section><section class="card"><h2>Your Leadership Pattern</h2><p>Primary leadership style: ${d.leadership_profile.primary_archetype}</p><p>Supporting leadership style: ${d.leadership_profile.supporting_archetype}</p><p>${d.leadership_profile.approved_strength_summary}</p><p>Your result is a guide, not a limit. All five leadership capacities already exist within you. This program helps you learn how to use them consciously.</p><a class="btn" href="/leadership-youth-result.html">View My Leadership Story</a></section><section class="card"><h2>Today’s Leadership Mission</h2><p>${d.current.mission}</p></section><section class="card"><h2>${d.session.title}</h2><h3>${d.session.featured_story.title}</h3><p>${d.session.featured_story.text}</p><details><summary>Explore More Week One Stories</summary>${d.session.additional_stories.map(s=>`<p>${s.title}</p>`).join('')}</details></section>`));}));
 r.get('/admin/the-leader-within', asyncRoute(async(req,res)=>{const d=await svc.facilitatorDashboard(pool,req);res.type('html').send(html('The Leader Within Mission Control', `<h1>The Leader Within Mission Control</h1><section class="grid"><article class="card">Active cohorts: ${d.metrics.active_cohorts}</article><article class="card">Active participants: ${d.metrics.active_participants}</article><article class="card">Reflections awaiting review: ${d.metrics.reflections_awaiting_review}</article><article class="card">Follow-up flags: ${d.metrics.follow_up_flags}</article></section><section class="card"><h2>Today’s Facilitator Plan</h2><p>${d.plan.learning_objective}</p><p>Story to deliver: ${d.plan.story_to_deliver}</p><h3>What to observe</h3><ul>${d.plan.what_to_observe.map(x=>`<li>${x}</li>`).join('')}</ul><h3>What not to do</h3><ul>${d.plan.what_not_to_do.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="grid">${d.cohorts.map(c=>`<article class="card"><h2>${c.name}</h2><p>${c.program_title}</p><p>Week ${c.current_week} • Session ${c.current_session}</p><p>${c.participant_count} enrolled</p><p>Assigned facilitator: ${c.assigned_facilitator_email||'Unassigned'}</p></article>`).join('')}</section>`));}));
 r.get('/admin/the-leader-within/cohorts/:cohortId', asyncRoute(async(req,res)=>res.redirect('/admin/the-leader-within')));
 r.get('/admin/the-leader-within/participants/:participantId', asyncRoute(async(req,res)=>{const p=await svc.participantProfile(pool,req);res.type('html').send(html('Participant Profile', `<h1>${p.overview.name||p.overview.email}</h1><section class="card"><h2>Overview</h2><p>${p.overview.program_title}</p><p>${p.overview.cohort_name}</p><p>Current week ${p.overview.current_week}; session ${p.overview.current_session}</p></section><section class="card"><h2>Leadership Profile</h2><p>Patterns shown at each checkpoint</p></section><section class="card"><h2>Practice History</h2></section><section class="card"><h2>Reflection History</h2></section><section class="card"><h2>Participation</h2></section><section class="card"><h2>PocketPT Summary</h2></section><section class="card"><h2>Facilitator Notes</h2><p>Private Facilitator Note</p></section>`));}));
 return r;
}
module.exports={createLeaderWithinRouter};
