"use strict";
const express = require("express");
const svc = require("./leaderWithinService");
function asyncRoute(fn){return (req,res)=>fn(req,res).catch(e=>res.status(e.status||500).json({error:e.status?e.message:"Request failed."}));}
function asyncHtml(fn){return (req,res)=>fn(req,res).catch(e=>{const status=e.status||500; const title=status===401?"Facilitator Sign In":status===403?"Leader Within access needed":"The Leader Within is unavailable"; const message=status===401?"Sign in with your authorized Garvey account to open The Leader Within facilitator dashboard.":status===403?"Your account is signed in, but it has not been assigned to a Leader Within facilitator role or cohort.":"We could not open this Leader Within page right now."; res.status(status).type("html").send(html(title, `<h1>${title}</h1><p>${message}</p><p><a class="btn" href="/the-leader-within.html">Return to The Leader Within</a> <a class="btn secondary" href="/index.html?next=${encodeURIComponent("/admin/the-leader-within")}">Continue to Secure Sign In</a></p>`));});}
function html(title, body){return `<!doctype html><html><head><title>${title}</title><link rel="stylesheet" href="/the-leader-within/programs/program.css"></head><body><main class="section">${body}</main></body></html>`;}
function safeReturnPath(v,fallback="/admin/the-leader-within"){const raw=String(v||"").trim(); if(!raw||raw.length>300) return fallback; if(!raw.startsWith("/")||raw.startsWith("//")||raw.includes("\\")) return fallback; try{const u=new URL(raw,"https://garvey.local"); if(u.origin!=="https://garvey.local") return fallback; const path=`${u.pathname}${u.search}${u.hash}`; return path.startsWith("/admin/the-leader-within")?path:fallback;}catch{return fallback;}}
function setSensitiveHeaders(_req,res,next){ res.setHeader("Cache-Control","no-store"); res.setHeader("X-Content-Type-Options","nosniff"); res.setHeader("Referrer-Policy","strict-origin-when-cross-origin"); res.setHeader("X-Frame-Options","DENY"); res.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()"); next(); }
function requestOrigin(req){ const o=String(req.headers.origin||"").trim(); if(o) return o; const r=String(req.headers.referer||"").trim(); if(!r) return ""; try{return new URL(r).origin;}catch{return "malformed";} }
function expectedOrigins(req){ const out=new Set([String(process.env.FRONTEND_ORIGIN||"").trim(),String(process.env.PUBLIC_APP_ORIGIN||"").trim(),String(process.env.STAGING_ORIGIN||"").trim(),String(process.env.PRODUCTION_ORIGIN||"").trim(),"https://garveyfrontend.onrender.com"].filter(Boolean)); const proto=String(req.headers["x-forwarded-proto"]||req.protocol||"http").split(",")[0].trim(); if(req.headers.host) out.add(`${proto}://${req.headers.host}`); if(process.env.NODE_ENV!=="production") { out.add("http://localhost:3000"); out.add("http://127.0.0.1:3000"); } return out; }
function requireTrustedOrigin(req,res,next){ if(!["POST","PUT","PATCH","DELETE"].includes(req.method)) return next(); const origin=requestOrigin(req); if(!origin || origin==="malformed" || !expectedOrigins(req).has(origin)) return res.status(403).json({error:"Trusted request origin required."}); next(); }
function csrfProtected(req){ return ["POST","PUT","PATCH","DELETE"].includes(req.method) && req.path !== "/api/the-leader-within/auth/sign-in"; }
function requireCsrf(req,res,next){ if(!csrfProtected(req)) return next(); const expected=req.leaderWithinYouthActor?.csrf_token || req.headers["x-leader-within-csrf-test-token"]; const supplied=String(req.headers["x-csrf-token"]||""); if(!expected || supplied !== expected) return res.status(403).json({error:"Valid CSRF token required."}); next(); }
async function loadYouth(pool, req, _res, next){ try{ req.leaderWithinYouthActor = await svc.resolveYouthSession(pool, req); next(); } catch { next(); } }
function createLeaderWithinRouter(pool){
 const r=express.Router();
 r.use(setSensitiveHeaders);
 r.use((req,res,next)=>loadYouth(pool,req,res,next));
 r.use(requireTrustedOrigin);
 r.use(requireCsrf);
 r.get('/the-leader-within/sign-in', (req,res)=>res.type('html').send(html('Welcome to The Leader Within', `<h1>Welcome to The Leader Within</h1><p>Enter your Leader ID and private sign-in code.</p><p>Your facilitator must add you to the program before you can sign in.</p><form id="youthSignInForm"><label>Leader ID <input name="leader_id" autocomplete="username"></label><label>Private sign-in code <input name="secret" type="password" autocomplete="current-password"></label><button class="btn" id="youthSignInButton">Start or Continue My Journey</button><p id="youthSignInStatus" role="alert"></p></form><section class="card"><h2>Help Signing In</h2><ul><li>Ask your facilitator to confirm your Leader ID.</li><li>Ask your facilitator to reset your temporary sign-in code.</li><li>Do not share your private code with other participants.</li></ul></section><script>document.getElementById("youthSignInForm").addEventListener("submit",async(e)=>{e.preventDefault();const f=e.currentTarget,b=document.getElementById("youthSignInButton"),s=document.getElementById("youthSignInStatus");b.disabled=true;s.textContent="";try{const r=await fetch("/api/the-leader-within/auth/sign-in",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(Object.fromEntries(new FormData(f).entries()))});const d=await r.json().catch(()=>({}));if(!r.ok) throw new Error(d.error||"We could not sign you in with those details.");window.location.href=d.route||"/the-leader-within/my-program";}catch(err){s.textContent=err.message||"We could not sign you in with those details.";b.disabled=false;}});</script>`)));
 r.get('/login', (req,res)=>res.redirect(302, `/index.html?next=${encodeURIComponent(safeReturnPath(req.query.next || req.query.returnTo))}`));
 r.get('/the-leader-within/facilitator/sign-in', asyncHtml(async(req,res)=>{ if(!req.authActor) return res.type('html').send(html('Facilitator Sign In', `<h1>Facilitator Sign In</h1><p>Sign in with your authorized Garvey account to open The Leader Within facilitator dashboard.</p><a class="btn" href="/index.html?next=${encodeURIComponent(safeReturnPath(req.query.next))}">Continue to Secure Sign In</a>`)); const d=await svc.facilitatorDashboard(pool,req); return res.redirect(302,safeReturnPath(req.query.next)); }));
 r.post('/api/the-leader-within/auth/sign-in', asyncRoute(async(req,res)=>{const out=await svc.signInYouth(pool,req); if(res.cookie) res.cookie(out.cookie,out.token,out.cookie_options); const {token,...safe}=out; res.json(safe);}));
 r.post('/api/the-leader-within/auth/first-login', asyncRoute(async(req,res)=>{const out=await svc.firstLogin(pool,req); if(res.cookie&&out.cookie) res.cookie(out.cookie,out.token,out.cookie_options); const {token,...safe}=out; res.json(safe);}));
 r.post('/api/the-leader-within/auth/sign-out', asyncRoute(async(req,res)=>{ await svc.revokeYouthSession(pool,req); if(res.clearCookie) res.clearCookie(svc.YOUTH_COOKIE,{path:'/the-leader-within'}); res.json({ok:true}); }));
 r.get('/api/the-leader-within/my-program', asyncRoute(async(req,res)=>res.json(await svc.getYouthDashboard(pool,req))));
 r.post('/api/the-leader-within/my-program/practice', asyncRoute(async(req,res)=>res.json(await svc.selectPractice(pool,req))));
 r.post('/api/the-leader-within/my-program/reflections', asyncRoute(async(req,res)=>res.json(await svc.submitReflection(pool,req))));
 r.post('/api/the-leader-within/my-program/shared-perspective', asyncRoute(async(req,res)=>res.json(await svc.submitSharedPerspective(pool,req))));
 r.get('/api/admin/the-leader-within', asyncRoute(async(req,res)=>res.json(await svc.facilitatorDashboard(pool,req))));
 r.get('/api/admin/the-leader-within/participants/:participantId', asyncRoute(async(req,res)=>res.json(await svc.participantProfile(pool,req))));
 r.post('/api/admin/the-leader-within/participants/:participantId/notes', asyncRoute(async(req,res)=>res.json(await svc.addNote(pool,req))));
 r.post('/api/admin/the-leader-within/cohorts/:cohortId/participants', asyncRoute(async(req,res)=>res.json(await svc.addParticipant(pool,req))));
 r.post('/api/admin/the-leader-within/participants/:participantId/reset-credential', asyncRoute(async(req,res)=>res.json(await svc.resetCredential(pool,req))));
 r.post('/api/admin/the-leader-within/enrollments/:enrollmentId/session', asyncRoute(async(req,res)=>res.json(await svc.facilitatorControl(pool,req))));
 r.get('/the-leader-within/my-program', asyncRoute(async(req,res)=>{const d=await svc.getYouthDashboard(pool,req);res.type('html').send(html('The Leader Within', `${d.empty_state?`<section class="hero"><h1>${d.empty_state.title}</h1><p>${d.empty_state.message}</p></section>`:`<section class="hero"><h1>The Leader Within</h1><p>Welcome Back, ${d.participant.first_name}</p><p>${d.program.title}</p><p>Week ${d.current.week} of ${d.program.duration_weeks} • ${d.current.phase}</p><p>Today: Session ${d.current.session} — ${d.current.session_title}</p></section><section class="card"><h2>Your Leadership Pattern</h2><p>Primary leadership style: ${d.leadership_profile?.primary_archetype||'Pending'}</p><p>Supporting leadership style: ${d.leadership_profile?.supporting_archetype||'Pending'}</p><p>${d.leadership_profile?.approved_strength_summary||''}</p><p>Your result is a guide, not a limit. All five leadership capacities already exist within you. This program helps you learn how to use them consciously.</p><a class="btn" href="/leadership-youth-result.html">View My Leadership Story</a></section><section class="card"><h2>Today’s Leadership Mission</h2><p>${d.current.mission}</p></section><section class="card"><h2>${d.session.title}</h2><h3>${d.session.featured_story.title}</h3><p>${d.session.featured_story.text}</p><details><summary>Explore More Week One Stories</summary>${d.session.additional_stories.map(s=>`<p>${s.title}</p>`).join('')}</details></section>`}`));}));
 r.get('/admin/the-leader-within', asyncHtml(async(req,res)=>{const d=await svc.facilitatorDashboard(pool,req);res.type('html').send(html('The Leader Within Mission Control', `<h1>The Leader Within Mission Control</h1><p>Facilitator: ${d.facilitator?.display_name||d.facilitator?.email||'Signed-in facilitator'}</p><p>Organization: ${d.facilitator?.tenant_slug||'Assigned tenant'}</p>${d.cohorts.length===0?`<section class="card"><h2>No Leader Within cohorts are currently assigned to you.</h2><p>${d.empty_state.message}</p>${d.empty_state.can_create_cohort?`<a class="btn" href="/admin/the-leader-within/bootstrap">Create Your First Leader Within Cohort</a>`:`<p>Contact a program administrator to receive a cohort assignment.</p>`}</section>`:``}<section class="grid"><article class="card">Active cohorts: ${d.metrics.active_cohorts}</article><article class="card">Active participants: ${d.metrics.active_participants}</article><article class="card">Current week/session: ${d.metrics.current_week}A</article><article class="card">Reflections awaiting review: ${d.metrics.reflections_awaiting_review}</article><article class="card">Follow-up flags: ${d.metrics.follow_up_flags}</article></section>${d.cohorts.map(c=>`<section class="card"><h2>${c.name}</h2><p>${c.participant_count} participants • Week ${c.current_week} Session ${c.current_session}</p><a class="btn" href="/admin/the-leader-within/cohorts/${c.id}/add-participant">Add Participant</a></section>`).join('')}<section class="card"><h2>Today’s facilitator plan</h2><p>${d.plan.session_title}</p><p>${d.plan.learning_objective}</p></section>`));}));
 r.get('/admin/the-leader-within/cohorts/:cohortId', asyncRoute(async(req,res)=>res.redirect('/admin/the-leader-within')));
 r.get('/admin/the-leader-within/cohorts/:cohortId/add-participant', asyncHtml(async(req,res)=>{const d=await svc.facilitatorDashboard(pool,req);res.type('html').send(html('Add Participant', `<h1>Add Participant</h1><p>Use the secure API route <code>/api/admin/the-leader-within/cohorts/${req.params.cohortId}/participants</code> to create the participant and show the temporary credential once.</p>`));}));
 r.get('/admin/the-leader-within/bootstrap', asyncHtml(async(req,res)=>{const d=await svc.facilitatorDashboard(pool,req); if(!d.empty_state.can_create_cohort) {const e=new Error('Administrator access required.'); e.status=403; throw e;} res.type('html').send(html('Create Your First Leader Within Cohort', `<h1>Create Your First Leader Within Cohort</h1><p>Admin-only setup for The Leader Within — 12-Week Program. Submit to <code>/api/admin/the-leader-within/bootstrap/cohort</code> with cohort_name, tenant_slug, location_id, facilitator_user_id, start_date, and status.</p>`));}));
 r.post('/api/admin/the-leader-within/bootstrap/cohort', asyncRoute(async(req,res)=>res.json(await svc.bootstrapCohort(pool,req))));
 r.get('/admin/the-leader-within/participants/:participantId', asyncRoute(async(req,res)=>{const p=await svc.participantProfile(pool,req);res.type('html').send(html('Participant Profile', `<h1>${p.overview.name||p.overview.email||p.overview.preferred_name}</h1><section class="card"><h2>Overview</h2><p>${p.overview.program_title}</p><p>${p.overview.cohort_name}</p><p>Current week ${p.overview.current_week}; session ${p.overview.current_session}</p></section><section class="card"><h2>Consent Status</h2><p>${p.overview.consent_status||'pending'}</p></section><section class="card"><h2>Facilitator Notes</h2><p>Private Facilitator Note</p></section>`));}));
 return r;
}
module.exports={createLeaderWithinRouter};
