"use strict";

const curriculum = require("../public/the-leader-within/programs/leader-within-program-data.js");
const SESSION_ORDER = ["A", "B", "C"];
const STORY_MAP = { A: "The Group Without a Captain", B: "The Practice That Started Falling Apart", C: "The Friend Who Did Not Say Much" };
const OPTIONAL_STORIES = ["The Plan Changed", "The Person Who Always Talks First"];
const PROGRAM_SLUG = "the-leader-within-12-week";
const DEV_ACTOR_FLAG = "LEADER_WITHIN_DEV_ACTOR_OVERRIDE";
const DEMO_BOOTSTRAP_FLAG = "LEADER_WITHIN_DEMO_BOOTSTRAP";
const ALLOWED_REFLECTION_TYPES = new Set(["before_practice", "story_response", "session_reflection", "after_practice", "group_debrief"]);
const ALLOWED_VISIBILITY = new Set(["participant_and_facilitator", "participant_only"]);
const ALLOWED_NOTE_TYPES = new Set(["private_facilitator_note", "attendance", "follow_up", "safety"]);
const ALLOWED_SESSION_ACTIONS = new Set(["open", "reopen", "make_up", "complete"]);

function fail(status, message) { const e = new Error(message); e.status = status; throw e; }
function norm(v) { return String(v || "").trim().toLowerCase(); }
function enabled(name) { return ["1", "true", "yes", "on"].includes(norm(process.env[name])); }
function nonProduction() { return process.env.NODE_ENV === "test" || process.env.NODE_ENV === "development"; }
function trustedActorFromRequest(req) {
  if (req.authActor?.email && req.authActor?.userId) {
    return { user_id: Number(req.authActor.userId), email: norm(req.authActor.email), authenticated: true, global_roles: req.authActor.isAdmin ? ["admin"] : [], tenant_memberships: [{ tenant_id: req.authActor.tenantId || null, tenant_slug: norm(req.authActor.tenantSlug), role: norm(req.authActor.role) }], active_tenant_id: req.authActor.tenantId || null, active_tenant_slug: norm(req.authActor.tenantSlug), role: norm(req.authActor.role), participant_id: Number(req.authActor.userId), is_admin: req.authActor.isAdmin === true, is_superadmin: req.authActor.isAdmin === true };
  }
  if (nonProduction() && enabled(DEV_ACTOR_FLAG) && req.headers["x-leader-within-dev-actor"]) {
    let data = {}; try { data = JSON.parse(String(req.headers["x-leader-within-dev-actor"])); } catch { fail(400, "Invalid development actor override."); }
    const role = norm(data.role || "youth_participant"); const email = norm(data.email); const userId = Number(data.user_id || data.userId || data.participant_id || 0);
    if (!email || !userId) fail(401, "Development actor override requires trusted fixture email and user_id.");
    if (!trustedActorFromRequest._logged) { console.warn("leader_within_dev_actor_override_active"); trustedActorFromRequest._logged = true; }
    return { user_id: userId, email, authenticated: true, global_roles: data.is_admin ? ["admin"] : [], tenant_memberships: [{ tenant_id: data.tenant_id || null, tenant_slug: norm(data.tenant_slug || data.tenant), role }], active_tenant_id: data.tenant_id || null, active_tenant_slug: norm(data.tenant_slug || data.tenant || "default"), role, participant_id: Number(data.participant_id || userId), is_admin: data.is_admin === true || role === "admin", is_superadmin: data.is_superadmin === true };
  }
  fail(401, "Authentication required.");
}
function isFacilitator(actor) { return actor.is_admin || ["facilitator", "coach", "staff", "admin"].includes(actor.role); }
function assertYouthOwns(actor, participantId, tenantSlug) { if (actor.is_admin) return; if (Number(actor.participant_id) !== Number(participantId)) fail(403, "Youth participants can only access their own program state."); if (tenantSlug && norm(tenantSlug) !== actor.active_tenant_slug) fail(403, "Tenant isolation enforced."); }
function assertFacilitatorForCohort(actor, cohort) { if (!isFacilitator(actor)) fail(403, "Facilitator role required."); if (actor.is_admin) return; if (norm(cohort.tenant_slug) !== actor.active_tenant_slug) fail(403, "Tenant isolation enforced."); if (!cohort.assigned_facilitator_email || norm(cohort.assigned_facilitator_email) !== actor.email) fail(403, "Facilitator is not assigned to this cohort."); }
function weekOne() { return curriculum.weeks[0]; }
function phaseForWeek(n) { return curriculum.phases[(curriculum.weeks.find((w) => w.n === n) || curriculum.weeks[0]).phase - 1]; }
function sessionTitle(code) { return ({ A: "Learn the Story", B: "Practice Through the Body", C: "Apply and Reflect" })[code] || "Learn the Story"; }
function currentMission(code, hasPractice) { if (code === "A") return hasPractice ? "Complete Today’s Reflection" : "Choose My Practice"; if (code === "B") return "Take It Into Training"; return "What Did the Group Teach You?"; }

async function ensureDemoState(pool, actor) {
  if (!nonProduction() || !enabled(DEMO_BOOTSTRAP_FLAG)) fail(403, "Demo bootstrap is disabled.");
  const tenant = await pool.query(`INSERT INTO tenants (slug,name) VALUES ($1,$2) ON CONFLICT (slug) DO UPDATE SET name=COALESCE(tenants.name,EXCLUDED.name) RETURNING id,slug`, [actor.active_tenant_slug || "demo", "Leader Within Demo Tenant"]);
  const user = await pool.query(`INSERT INTO users (email,tenant_id,name) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,email) DO UPDATE SET name=COALESCE(users.name,EXCLUDED.name) RETURNING id,email,name`, [actor.email, tenant.rows[0].id, actor.email.split("@")[0]]);
  const program = await pool.query(`SELECT id FROM leader_within_programs WHERE slug=$1`, [PROGRAM_SLUG]);
  const cohort = await pool.query(`INSERT INTO leader_within_cohorts (tenant_id,name,program_id,location_id,current_week,current_session,assigned_facilitator_email,is_demo) VALUES ($1,'Leader Within Demo Cohort',$2,'Demo',1,'A',$3,TRUE) RETURNING id`, [tenant.rows[0].id, program.rows[0].id, actor.email]);
  const enrollment = await pool.query(`INSERT INTO leader_within_program_enrollments (participant_id,program_id,cohort_id,tenant_id,location_id,status,current_week,current_session,is_demo) VALUES ($1,$2,$3,$4,'Demo','active',1,'A',TRUE) ON CONFLICT (participant_id,program_id) DO UPDATE SET updated_at=NOW() RETURNING *`, [user.rows[0].id, program.rows[0].id, cohort.rows[0].id, tenant.rows[0].id]);
  await pool.query(`INSERT INTO leader_within_session_progress (enrollment_id,week_number,session_code,status,opened_at,is_demo) VALUES ($1,1,'A','available',NOW(),TRUE) ON CONFLICT DO NOTHING`, [enrollment.rows[0].id]);
  return enrollment.rows[0];
}

async function loadYouthEnrollment(pool, actor) {
  const result = await pool.query(`SELECT e.*, u.email participant_email, u.name participant_name, t.slug tenant_slug, p.title program_title, p.duration_weeks, c.name cohort_name, c.location_id, c.alternate_story_title FROM leader_within_program_enrollments e JOIN users u ON u.id=e.participant_id JOIN tenants t ON t.id=e.tenant_id JOIN leader_within_programs p ON p.id=e.program_id LEFT JOIN leader_within_cohorts c ON c.id=e.cohort_id WHERE e.participant_id=$1 AND lower(t.slug)=lower($2) AND e.status='active' LIMIT 1`, [actor.participant_id, actor.active_tenant_slug]);
  return result.rows[0] || null;
}
function youthEmptyState() { return { empty_state: { title: "The Leader Within", message: "You are not currently enrolled in a Leader Within program.", actions: ["Return to Youth Development", "View The Leader Within", "Contact your program facilitator"] } }; }
function facilitatorEmptyState() { return { empty_state: { message: "No Leader Within cohorts are currently assigned to you." } }; }
async function getYouthDashboard(pool, req) {
  const actor = trustedActorFromRequest(req); const row = await loadYouthEnrollment(pool, actor); if (!row) return youthEmptyState(); assertYouthOwns(actor, row.participant_id, row.tenant_slug);
  const practice = (await pool.query(`SELECT practice_id, participant_reason, status FROM leader_within_practice_selections WHERE enrollment_id=$1 AND week_number=$2`, [row.id, row.current_week])).rows[0] || null;
  const progress = (await pool.query(`SELECT session_code,status FROM leader_within_session_progress WHERE enrollment_id=$1 AND week_number=$2 ORDER BY session_code`, [row.id, row.current_week])).rows;
  const snap = (await pool.query(`SELECT completed_at, primary_archetype, supporting_archetype, approved_strength_summary, approved_growth_summary, assessment_version, checkpoint_type FROM leader_within_assessment_snapshots WHERE enrollment_id=$1 ORDER BY completed_at DESC NULLS LAST, id DESC LIMIT 1`, [row.id])).rows[0] || null;
  const w = weekOne(); const phase = phaseForWeek(row.current_week); const featured = row.alternate_story_title || STORY_MAP[row.current_session] || STORY_MAP.A;
  return { program: { title: row.program_title, duration_weeks: row.duration_weeks }, participant: { first_name: (row.participant_name || row.participant_email || "Friend").split(/[ @]/)[0] }, current: { phase: `Phase ${phase.id}: ${phase.name}`, week: row.current_week, session: row.current_session, session_title: sessionTitle(row.current_session), mission: currentMission(row.current_session, !!practice) }, leadership_profile: snap, practice, progress, session: buildYouthSession(row.current_session, w, featured, practice) };
}
function buildYouthSession(code, w, featuredTitle, practice) { const featured = w.stories.find((s) => s.title === featuredTitle) || w.stories.find((s) => s.title === STORY_MAP[code]) || w.stories[0]; const extra = w.stories.filter((s) => s.title !== featured.title).map((s) => ({ title: s.title, collapsed: true })); if (code === "B") return { code, title: "Session B — Practice Through the Body", featured_story: featured, selected_practice: practice, observation_lens: "Notice when leadership appears during movement, effort, safety, support, recovery, or adjustment.", pocketpt_copy: "Your PocketPT fitness session will match your current ability, safety needs, and personal training plan. During the session, notice where leadership appears.", pocketpt_placeholder: "Your PocketPT fitness session will appear here when program enrollment is connected.", additional_stories: extra }; if (code === "C") return { code, title: "Session C — Apply and Reflect", challenge: w.sessionC.title, featured_story: featured, group_prompts: w.sessionC.debrief, group_perspective_fields: w.groupPerspective.fields, additional_stories: extra }; return { code, title: "Session A — Learn the Story", week_title: w.title, core_question: w.q, key_lesson: w.story, featured_story: featured, prompts: featured.prompts, before_prompts: w.before, practice_bank: w.practiceBank, additional_stories: extra }; }
async function requireYouthEnrollment(pool, req) { const actor = trustedActorFromRequest(req); const row = await loadYouthEnrollment(pool, actor); if (!row) fail(403, "Active Leader Within enrollment required."); assertYouthOwns(actor, row.participant_id, row.tenant_slug); return { actor, row }; }
async function selectPractice(pool, req) { const { row } = await requireYouthEnrollment(pool, req); const id = String(req.body.practice_id || "").trim(); if (!weekOne().practiceBank.some((p) => p.title === id)) fail(400, "Invalid participant-controlled practice selection."); await pool.query(`INSERT INTO leader_within_practice_selections (enrollment_id,week_number,practice_id,participant_reason,status) VALUES ($1,$2,$3,$4,'selected') ON CONFLICT (enrollment_id,week_number) DO UPDATE SET practice_id=EXCLUDED.practice_id, participant_reason=EXCLUDED.participant_reason, selected_at=NOW(), updated_at=NOW()`, [row.id, row.current_week, id, String(req.body.participant_reason || "").slice(0, 1000) || null]); return { ok: true, practice_id: id }; }
async function submitReflection(pool, req) { const { row } = await requireYouthEnrollment(pool, req); const type = String(req.body.reflection_type || "before_practice"); const text = String(req.body.response_text || "").trim(); const visibility = String(req.body.visibility || "participant_and_facilitator"); if (!ALLOWED_REFLECTION_TYPES.has(type)) fail(400, "Invalid reflection type."); if (!ALLOWED_VISIBILITY.has(visibility)) fail(400, "Invalid visibility."); if (!text || text.length > 5000) fail(400, "response_text required and must be 5000 characters or fewer."); await pool.query(`INSERT INTO leader_within_reflections (enrollment_id,week_number,session_code,reflection_type,prompt_id,response_text,visibility) VALUES ($1,$2,$3,$4,$5,$6,$7)`, [row.id, row.current_week, row.current_session, type, req.body.prompt_id || null, text, visibility]); return { ok: true }; }
async function submitSharedPerspective(pool, req) { const { row } = await requireYouthEnrollment(pool, req); const clean = (v) => String(v || "").slice(0, 2000) || null; await pool.query(`INSERT INTO leader_within_shared_perspectives (enrollment_id,week_number,perspective_heard,idea_to_consider,group_difference) VALUES ($1,$2,$3,$4,$5)`, [row.id, row.current_week, clean(req.body.perspective_heard), clean(req.body.idea_to_consider), clean(req.body.group_difference)]); return { ok: true }; }
async function facilitatorDashboard(pool, req) { const actor = trustedActorFromRequest(req); if (!isFacilitator(actor)) fail(403, "Facilitator role required."); const cohorts = (await pool.query(`SELECT c.*, t.slug tenant_slug, p.title program_title, COUNT(e.id)::int participant_count FROM leader_within_cohorts c JOIN tenants t ON t.id=c.tenant_id JOIN leader_within_programs p ON p.id=c.program_id LEFT JOIN leader_within_program_enrollments e ON e.cohort_id=c.id WHERE ($1::boolean OR (lower(t.slug)=lower($2) AND lower(c.assigned_facilitator_email)=lower($3))) GROUP BY c.id,t.slug,p.title ORDER BY c.id`, [actor.is_admin, actor.active_tenant_slug, actor.email])).rows; return { ...facilitatorEmptyState(), metrics: { active_cohorts: cohorts.length, active_participants: cohorts.reduce((n,c)=>n+c.participant_count,0), current_week: 1, today_sessions: cohorts.length, check_ins_today: 0, reflections_awaiting_review: 0, missed_sessions: 0, follow_up_flags: 0, pocketpt_summaries_awaiting_review: 0 }, cohorts, plan: { session_title: "Session A — Learn the Story", learning_objective: weekOne().facilitator.objective, story_to_deliver: STORY_MAP.A, required_materials: ["Story card", "Practice bank", "Reflection prompts"], discussion_prompts: weekOne().stories[0].prompts, practice_options: weekOne().practiceBank.map(p=>p.title), what_to_observe: weekOne().facilitator.observe, what_not_to_do: weekOne().facilitator.notDo, completion_criteria: weekOne().completion, pocketpt_lens: "Observe leadership during safe individualized movement; do not prescribe a universal workout." } }; }
async function participantProfile(pool, req) { const actor = trustedActorFromRequest(req); const id = Number(req.params.participantId); const profile = await pool.query(`SELECT e.*, u.email,u.name,c.name cohort_name,c.location_id,c.assigned_facilitator_email,t.slug tenant_slug,p.title program_title FROM leader_within_program_enrollments e JOIN users u ON u.id=e.participant_id JOIN leader_within_cohorts c ON c.id=e.cohort_id JOIN tenants t ON t.id=e.tenant_id JOIN leader_within_programs p ON p.id=e.program_id WHERE e.participant_id=$1 LIMIT 1`, [id]); if (!profile.rows[0]) fail(404, "Not found"); assertFacilitatorForCohort(actor, profile.rows[0]); const enrollmentId = profile.rows[0].id; const [snapshots, practices, reflections, progress, pocketpt, notes] = await Promise.all([ pool.query(`SELECT completed_at,primary_archetype,supporting_archetype,approved_strength_summary,approved_growth_summary,assessment_version,checkpoint_type FROM leader_within_assessment_snapshots WHERE enrollment_id=$1 ORDER BY id DESC`, [enrollmentId]), pool.query(`SELECT week_number,practice_id,participant_reason,attempted_at,status,reflection_summary FROM leader_within_practice_selections WHERE enrollment_id=$1 ORDER BY week_number`, [enrollmentId]), pool.query(`SELECT week_number,session_code,reflection_type,prompt_id,response_text,visibility,submitted_at FROM leader_within_reflections WHERE enrollment_id=$1 AND visibility='participant_and_facilitator' ORDER BY submitted_at DESC`, [enrollmentId]), pool.query(`SELECT week_number,session_code,status,checked_in_at,completed_at FROM leader_within_session_progress WHERE enrollment_id=$1 ORDER BY week_number,session_code`, [enrollmentId]), pool.query(`SELECT week_number,session_code,assignment_status,completion_status,completed_at,effort_check_status,recovery_check_status,approved_coaching_summary,follow_up_flag FROM leader_within_pocketpt_activity_summaries WHERE enrollment_id=$1`, [enrollmentId]), pool.query(`SELECT note_type,note_text,visibility,created_at FROM leader_within_facilitator_notes WHERE enrollment_id=$1 ORDER BY created_at DESC`, [enrollmentId]) ]); return { overview: profile.rows[0], leadership_profile: { label: "Patterns shown at each checkpoint", snapshots: snapshots.rows }, practice_history: practices.rows, reflection_history: reflections.rows, participation: progress.rows, pocketpt_summary: pocketpt.rows, facilitator_notes: notes.rows }; }
async function facilitatorControl(pool, req) { const actor = trustedActorFromRequest(req); const enrollmentId = Number(req.params.enrollmentId); const e = (await pool.query(`SELECT e.*,c.assigned_facilitator_email,c.alternate_story_title,t.slug tenant_slug FROM leader_within_program_enrollments e JOIN leader_within_cohorts c ON c.id=e.cohort_id JOIN tenants t ON t.id=e.tenant_id WHERE e.id=$1`, [enrollmentId])).rows[0]; if (!e) fail(404, "Not found"); assertFacilitatorForCohort(actor, e); const action = String(req.body.action || "open"); const session = String(req.body.session_code || e.current_session || "A").toUpperCase(); if (!ALLOWED_SESSION_ACTIONS.has(action)) fail(400, "Invalid session action."); if (!SESSION_ORDER.includes(session)) fail(400, "Invalid session code."); if (req.body.alternate_story_title && ![...Object.values(STORY_MAP), ...OPTIONAL_STORIES].includes(req.body.alternate_story_title)) fail(400, "Invalid story title."); const status = action === "reopen" ? "available" : action === "make_up" ? "missed" : action === "complete" ? "completed" : "available"; await pool.query(`INSERT INTO leader_within_session_progress (enrollment_id,week_number,session_code,status,opened_at,completed_at,completed_by) VALUES ($1,$2,$3,$4,NOW(),CASE WHEN $4='completed' THEN NOW() ELSE NULL END,$5) ON CONFLICT (enrollment_id,week_number,session_code) DO UPDATE SET status=EXCLUDED.status, opened_at=COALESCE(leader_within_session_progress.opened_at,NOW()), completed_at=EXCLUDED.completed_at, completed_by=EXCLUDED.completed_by, updated_at=NOW()`, [enrollmentId, e.current_week, session, status, actor.email]); if (req.body.alternate_story_title) await pool.query(`UPDATE leader_within_cohorts SET alternate_story_title=$1, updated_at=NOW() WHERE id=$2`, [req.body.alternate_story_title, e.cohort_id]); return { ok: true, status }; }
async function addNote(pool, req) { const actor = trustedActorFromRequest(req); const profile = await participantProfile(pool, req); const note = String(req.body.note_text || "").trim(); const noteType = String(req.body.note_type || "private_facilitator_note"); if (!ALLOWED_NOTE_TYPES.has(noteType)) fail(400, "Invalid note type."); if (!note || note.length > 5000) fail(400, "note_text required and must be 5000 characters or fewer."); await pool.query(`INSERT INTO leader_within_facilitator_notes (participant_id,cohort_id,enrollment_id,author_id,note_type,note_text,visibility) VALUES ($1,$2,$3,$4,$5,$6,'facilitator_private')`, [profile.overview.participant_id, profile.overview.cohort_id, profile.overview.id, actor.user_id, noteType, note]); return { ok: true }; }
module.exports = { getYouthDashboard, selectPractice, submitReflection, submitSharedPerspective, facilitatorDashboard, participantProfile, facilitatorControl, addNote, ensureDemoState, trustedActorFromRequest, STORY_MAP, OPTIONAL_STORIES };
