// FILE: server/siteGenerator.js
// Command B: config-driven multi-tenant site pages stored in tenant_sites.pages JSONB
//
// API usage (server/index.js already wired):
// - POST /api/site/generate  { tenant, site, features }
// - GET  /t/:slug/site       renders landing HTML
//
// generateTenantSite(...) returns:
// { version: number, pages: { landing: "<html...>", checkout: "...", community: "..." } }

"use strict";

function esc(str) {
  return String(str ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function bool(v, fallback) {
  if (typeof v === "boolean") return v;
  return Boolean(fallback);
}

function pickTheme(site = {}) {
  const primary = site.primary_color || "#facc15"; // gold
  const bg = site.bg_color || "#000000";
  const card = site.card_color || "#111111";
  const text = site.text_color || "#ffffff";
  const accent = site.accent_color || "#ef4444";
  return { primary, bg, card, text, accent };
}

function landingHtml({ tenantSlug, config }) {
  const site = config?.site || {};
  const features = config?.features || {};
  const theme = pickTheme(site);

  const businessName = site.business_name || tenantSlug;
  const headline = site.headline || `Join ${businessName} Community & Earn Rewards`;
  const subhead =
    site.subheadline ||
    "Earn points for check-ins, reviews, referrals, and get personalized recommendations.";

  const rewardName = site.reward_name || "Credits";

  const showRewards = bool(features.rewards, true);
  const showIntake = bool(features.quiz, true);
  const showReviews = bool(features.reviews, true);
  const showStore = bool(features.store, false);

  const intakeLink = `/intake.html?tenant=${encodeURIComponent(tenantSlug)}`;
  const cxLink = `/index.html?tenant=${encodeURIComponent(tenantSlug)}`;
  const dashLink = `/dashboard.html?tenant=${encodeURIComponent(tenantSlug)}`;
  const adminLink = `/admin.html?tenant=${encodeURIComponent(tenantSlug)}`;
  const vocLink = `/voc.html?tenant=${encodeURIComponent(tenantSlug)}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${esc(businessName)} — Community</title>
  <style>
    body { font-family: Arial, sans-serif; background:${esc(theme.bg)}; color:${esc(theme.text)}; padding:24px; }
    .card { background:${esc(theme.card)}; border:2px solid ${esc(theme.primary)}; padding:24px; border-radius:16px; max-width:860px; margin:0 auto; }
    h1 { color:${esc(theme.primary)}; margin:0 0 8px; }
    p { color:#cbd5e1; margin:0 0 14px; }
    .ctaRow { display:flex; gap:12px; flex-wrap:wrap; margin:14px 0; }
    a.btn { display:inline-block; padding:12px 14px; border-radius:12px; border:2px solid #000; background:${esc(
      theme.primary
    )}; color:#000; font-weight:800; text-decoration:none; }
    a.btn:hover { background:${esc(theme.accent)}; color:#fff; }
    .grid { display:grid; grid-template-columns: 1fr 1fr; gap:12px; margin-top:14px; }
    .box { background:#0b1020; border:1px solid #334155; border-radius:12px; padding:14px; }
    .label { color:#93c5fd; font-weight:700; margin-bottom:6px; }
    .meta { color:#94a3b8; font-size:12px; margin-top:14px; }
    .pill { display:inline-block; padding:4px 10px; border-radius:999px; background:#111827; border:1px solid #334155; color:#e5e7eb; font-size:12px; margin-right:6px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="pill">Tenant: ${esc(tenantSlug)}</div>
    ${showRewards ? `<div class="pill">Rewards: ${esc(rewardName)}</div>` : ""}
    ${showStore ? `<div class="pill">Store: enabled</div>` : `<div class="pill">Store: off</div>`}

    <h1>${esc(headline)}</h1>
    <p>${esc(subhead)}</p>

    <div class="ctaRow">
      ${showIntake ? `<a class="btn" href="${esc(intakeLink)}">Take the Assessment</a>` : ""}
      <a class="btn" href="${esc(cxLink)}">Earn Points (Actions)</a>
      <a class="btn" href="${esc(dashLink)}">Owner Dashboard</a>
    </div>

    <div class="grid">
      <div class="box">
        <div class="label">What you can do</div>
        <ul>
          <li>Check in and earn points</li>
          ${showReviews ? "<li>Leave reviews (photo/video optional)</li>" : ""}
          <li>Refer friends to grow the community</li>
          <li>Join the list for offers + updates</li>
        </ul>
      </div>

      <div class="box">
        <div class="label">Owner controls</div>
        <ul>
          <li><a href="${esc(adminLink)}">Admin config</a> (toggle features)</li>
          <li><a href="${esc(dashLink)}">Dashboard</a> (analytics)</li>
          <li><a href="${esc(vocLink)}">VOC Intake</a> (customer voice)</li>
        </ul>
      </div>
    </div>

    <div class="meta">
      Generated by Garvey Site Generator (Command B). Preview route: <code>/t/${esc(tenantSlug)}/site</code>
    </div>
  </div>
</body>
</html>`;
}

function generateTenantSite({ tenantSlug, config }) {
  const version = 1;

  const pages = {
    landing: landingHtml({ tenantSlug, config })
  };

  return { version, pages };
}

module.exports = { generateTenantSite };
