'use strict';
const crypto=require('node:crypto');const reduceExperience=require('../../engine/reducer');const {PersistenceError,fail}=require('../persistenceTypes');
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
class PostgresTransactionalExperienceRepository{
 constructor({pool,sessions,events,releases,idempotency,reducer=reduceExperience,eventId=(s,n)=>`${s}:${n}`}){Object.assign(this,{pool,sessions,events,releases,idempotency,reducer,eventId});}
 async transactionallyApplyAction(input){if(!input.idempotency_key)fail('IDEMPOTENCY_KEY_REQUIRED');const client=await this.pool.connect();try{await client.query('BEGIN');const session=await this.sessions.getOwnedSession(input,client,{lock:true});const requestHash=digest({action:input.action,expected_revision:input.expected_revision});const prior=await this.idempotency.find(input.session_id,input.idempotency_key,client);if(prior){if(prior.request_hash!==requestHash)fail('IDEMPOTENCY_CONFLICT');await client.query('COMMIT');return prior.response_json;}if(session.revision!==input.expected_revision)fail('SESSION_REVISION_CONFLICT');const release=await this.releases.getPinned(session.release_id,client);const experience=(release.manifest_json.experiences||[]).find(x=>x.experience_id===session.experience_id&&x.experience_version===session.experience_version);if(!experience)fail('PINNED_EXPERIENCE_NOT_FOUND');const result=this.reducer({experience,session:session.state_json,action:structuredClone(input.action)});if(!result?.valid)fail('REDUCER_REJECTED_ACTION','Reducer rejected action',result?.errors);if(result.nextSession.revision!==session.revision+1)fail('PERSISTENCE_TRANSACTION_FAILED','Reducer revision contract violated');const existing=await this.events.listSessionEvents(session.session_id,client);const at=input.occurred_at;const persisted=result.events.map((event,i)=>({event_id:this.eventId(session.session_id,existing.length+i+1),session_id:session.session_id,sequence:existing.length+i+1,event_type:event.type,idempotency_key:`${input.idempotency_key}:${i}`,event_json:event,occurred_at:at,received_at:input.received_at||at}));await this.events.append(persisted,client);session.state_json=result.nextSession;session.status=result.nextSession.status;const saved=await this.sessions.updateSnapshot(session,input.expected_revision,at,client);const response={...result,persisted_revision:saved.revision,persisted_events:persisted};await this.idempotency.store({session_id:session.session_id,idempotency_key:input.idempotency_key,request_hash:requestHash,response_json:response,resulting_revision:saved.revision},client);await client.query('COMMIT');return response;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(error instanceof PersistenceError)throw error;throw new PersistenceError('PERSISTENCE_TRANSACTION_FAILED','Transaction failed');}finally{client.release();}}
 async transactionallySetStatus(input,status){if(!['paused','abandoned'].includes(status))fail('VALIDATION_FAILED');if(!input.idempotency_key)fail('IDEMPOTENCY_KEY_REQUIRED');const client=await this.pool.connect();try{await client.query('BEGIN');const session=await this.sessions.getOwnedSession(input,client,{lock:true});const requestHash=digest({status,expected_revision:input.expected_revision}),prior=await this.idempotency.find(input.session_id,input.idempotency_key,client);if(prior){if(prior.request_hash!==requestHash)fail('IDEMPOTENCY_CONFLICT');await client.query('COMMIT');return prior.response_json;}if(session.revision!==input.expected_revision)fail('SESSION_REVISION_CONFLICT');await this.releases.getPinned(session.release_id,client);session.state_json={...session.state_json,status,revision:session.revision+1};session.status=status;const existing=await this.events.listSessionEvents(session.session_id,client),sequence=existing.length+1,at=input.occurred_at;const event={event_id:this.eventId(session.session_id,sequence),session_id:session.session_id,sequence,event_type:`experience_${status}`,idempotency_key:`${input.idempotency_key}:0`,event_json:{type:`experience_${status}`,revision:session.revision+1},occurred_at:at,received_at:input.received_at||at};await this.events.append([event],client);const saved=await this.sessions.updateSnapshot(session,input.expected_revision,at,client),response={persisted_revision:saved.revision,persisted_events:[event],session:saved};await this.idempotency.store({session_id:session.session_id,idempotency_key:input.idempotency_key,request_hash:requestHash,response_json:response,resulting_revision:saved.revision},client);await client.query('COMMIT');return response;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(error instanceof PersistenceError)throw error;throw new PersistenceError('PERSISTENCE_TRANSACTION_FAILED','Transaction failed');}finally{client.release();}}
}
module.exports=PostgresTransactionalExperienceRepository;
