'use strict';
const registry=require('../../domain/gateRegistry');const q=require('./postgresQueries');const {sessionRow,json}=require('./postgresSerialization');const {deserializeSessionState}=require('../serialization');const {fail}=require('../persistenceTypes');
class PostgresSessionRepository{
 constructor(db,releases){this.db=db;this.releases=releases;}
 async createSession(input,client=this.db){if(!registry.getById(input.gate_id))fail('INVALID_GATE_ID');await this.releases.getForNewSession(input.release_id,client);const state=deserializeSessionState(input.state_json);try{const r=await client.query(`INSERT INTO gates_v2_experience_sessions(session_id,parent_profile_id,child_id,gate_id,experience_id,release_id,experience_version,age_band,locale,narration_variant_id,feature_variant_json,state_json,revision,status,started_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15) RETURNING *`,[input.session_id,input.parent_profile_id,input.child_id,input.gate_id,input.experience_id,input.release_id,input.experience_version,input.age_band,input.locale,input.narration_variant_id||null,input.feature_variant_json||{},json(state),state.revision,input.status||state.status,input.created_at]);return sessionRow(r.rows[0]);}catch(e){if(e.code==='23505')fail('SESSION_ALREADY_EXISTS');throw e;}}
 async getSessionById(id,client=this.db,{lock=false}={}){const row=(await client.query(lock?q.lockedSession:q.sessionById,[id])).rows[0];if(!row)fail('SESSION_NOT_FOUND');return sessionRow(row);}
 async getOwnedSession(ctx,client=this.db,options){const row=await this.getSessionById(ctx.session_id,client,options);if(String(row.parent_profile_id)!==String(ctx.parent_profile_id))fail('SESSION_OWNERSHIP_MISMATCH');if(String(row.child_id)!==String(ctx.child_id))fail('CHILD_OWNERSHIP_MISMATCH');return row;}
 async listChildSessions(ctx,client=this.db){return (await client.query(q.ownedSessions,[ctx.parent_profile_id,ctx.child_id])).rows.map(sessionRow);}
 async resumeSession(ctx,client=this.db){const row=await this.getOwnedSession(ctx,client);await this.releases.getPinned(row.release_id,client);return row;}
 async updateSnapshot(session,expected,at,client=this.db){const r=await client.query(`UPDATE gates_v2_experience_sessions SET state_json=$2,revision=revision+1,status=$3,updated_at=$4,completed_at=CASE WHEN $3='completed' THEN COALESCE(completed_at,$4) ELSE completed_at END,abandoned_at=CASE WHEN $3='abandoned' THEN COALESCE(abandoned_at,$4) ELSE abandoned_at END WHERE session_id=$1 AND revision=$5 RETURNING *`,[session.session_id,json(session.state_json),session.status,at,expected]);if(!r.rowCount)fail('SESSION_REVISION_CONFLICT');return sessionRow(r.rows[0]);}
}
module.exports=PostgresSessionRepository;
