"use strict";

const { EVIDENCE_STATUS_TAG } = require("../tdeGovernance");

const TRAIT_MAPPING_CONTRACT = Object.freeze({
  schema_version: "1.0",
  calibration_version: "tde-calibration-v0",
  traits: Object.freeze({
    SR: Object.freeze({
      required_signal_types: Object.freeze(["strategy_use_presence", "context_consistency"]),
      optional_signal_types: Object.freeze(["rule_adherence", "reengagement_latency", "process_efficiency"]),
      allowed_source_types: Object.freeze(["task_event", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_only_duration_without_regulation_marker"]),
      contamination_rules: Object.freeze(["separate_self_regulation_vs_persistence"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "sr_default_v1" }),
      missing_data_policy: "flag_provisional_if_source_diversity_below_threshold",
    }),
    CQ: Object.freeze({
      required_signal_types: Object.freeze(["inquiry_depth"]),
      optional_signal_types: Object.freeze(["behavior_frequency", "justification_quality", "option_diversity"]),
      allowed_source_types: Object.freeze(["item_response", "task_event", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_only_enthusiasm_without_inquiry"]),
      contamination_rules: Object.freeze(["separate_curiosity_vs_creativity"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "cq_default_v1" }),
      missing_data_policy: "hold_or_provisional_when_single_source",
    }),
    CR: Object.freeze({
      required_signal_types: Object.freeze(["artifact_quality", "option_diversity"]),
      optional_signal_types: Object.freeze(["attempt_quality_change", "behavior_frequency"]),
      allowed_source_types: Object.freeze(["task_event", "item_response", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_only_question_volume"]),
      contamination_rules: Object.freeze(["separate_reasoning_vs_creativity", "separate_curiosity_vs_creativity"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "cr_default_v1" }),
      missing_data_policy: "hide_if_required_signal_types_missing",
    }),
    RS: Object.freeze({
      required_signal_types: Object.freeze(["justification_quality", "execution_accuracy"]),
      optional_signal_types: Object.freeze(["decision_quality", "improvement_delta"]),
      allowed_source_types: Object.freeze(["task_event", "item_response", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_correctness_without_reasoning_explanation"]),
      contamination_rules: Object.freeze(["separate_reasoning_vs_creativity"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "rs_default_v1" }),
      missing_data_policy: "provisional_when_explanation_signals_sparse",
    }),
    PS: Object.freeze({
      required_signal_types: Object.freeze(["attempt_quality_change", "reengagement_latency"]),
      optional_signal_types: Object.freeze(["completion_quality", "strategy_shift_detected"]),
      allowed_source_types: Object.freeze(["task_event", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_only_time_on_task"]),
      contamination_rules: Object.freeze(["separate_self_regulation_vs_persistence"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "ps_default_v1" }),
      missing_data_policy: "provisional_when_challenge_task_missing",
    }),
    FB: Object.freeze({
      required_signal_types: Object.freeze(["improvement_delta"]),
      optional_signal_types: Object.freeze(["attempt_quality_change", "error_reduction"]),
      allowed_source_types: Object.freeze(["task_event", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_simple_compliance_without_delta"]),
      contamination_rules: Object.freeze(["separate_feedback_responsiveness_vs_compliance"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "fb_default_v1" }),
      missing_data_policy: "hide_when_no_iteration_evidence",
    }),
    DE: Object.freeze({
      required_signal_types: Object.freeze(["domain_commitment_language"]),
      optional_signal_types: Object.freeze(["behavior_frequency", "progress_attribution_quality"]),
      allowed_source_types: Object.freeze(["task_event", "item_response", "observation"]),
      minimum_signal_count: 2,
      minimum_source_diversity: 2,
      exclusion_rules: Object.freeze(["exclude_if_single_window_only"]),
      contamination_rules: Object.freeze(["separate_domain_engagement_vs_temporary_excitement"]),
      weighting_policy: Object.freeze({ status: EVIDENCE_STATUS_TAG.CALIBRATION_VARIABLE, policy_code: "de_default_v1" }),
      missing_data_policy: "require_longitudinal_windows_or_flag_low_evidence",
    }),
  }),
});

module.exports = {
  TRAIT_MAPPING_CONTRACT,
};
