"use strict";

const YOUTH_TALENT_BANK_1 = Object.freeze({
  bank_id: "YOUTH_TALENT_BANK_1",
  bank_name: "Youth Talent Baseline Authored Bank 1",
  bank_version: "1.0.0-phase-4",
  domain_code: "YOUTH_DEVELOPMENT",
  tasks: Object.freeze([
    {
      task_id: "YT_B1_SR_01",
      trait_code: "SR",
      task_class: "PRF",
      prompt: "Follow a 5-step build sequence to assemble a paper tower that stands for 30 seconds.",
      instructions:
        "Give the child the printed sequence and materials. Score whether steps are followed in order, whether pacing is managed without derailment, and whether the final tower meets stability criteria.",
      expected_signal_types: Object.freeze(["rule_adherence", "process_efficiency", "completion_quality"]),
      scoring_type: "analytic",
      evidence_source: "child_task",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_SR_02",
      trait_code: "SR",
      task_class: "OBS",
      prompt: "Observe task-regulation behaviors during a 12-minute independent work interval.",
      instructions:
        "Record frequency of self-initiated restarts after distraction, visible calming/focus strategy use, and consistency of on-task behavior across three 4-minute segments.",
      expected_signal_types: Object.freeze(["behavior_frequency", "strategy_use_presence", "context_consistency"]),
      scoring_type: "frequency",
      evidence_source: "teacher_observation",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_SR_03",
      trait_code: "SR",
      task_class: "RET",
      prompt: "Retry the same sequencing task after one coaching cue on attention reset.",
      instructions:
        "Compare first and second attempts on interruption recovery time, step-order errors, and restart latency after distraction.",
      expected_signal_types: Object.freeze(["improvement_delta", "error_reduction", "reengagement_latency"]),
      scoring_type: "delta",
      evidence_source: "child_retry",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_CQ_01",
      trait_code: "CQ",
      task_class: "SCT",
      prompt: "Scenario: Your class plant is wilting. What would you ask and check before deciding what to do?",
      instructions:
        "Score number and quality of information-seeking questions, whether the child identifies missing information, and depth of follow-up inquiry.",
      expected_signal_types: Object.freeze(["inquiry_depth", "justification_quality", "decision_quality"]),
      scoring_type: "rubric",
      evidence_source: "child_scenario",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_CQ_02",
      trait_code: "CQ",
      task_class: "PRF",
      prompt: "Complete the core puzzle, then choose up to two optional challenge cards to investigate.",
      instructions:
        "Measure whether optional exploration is attempted, whether the child tests alternatives, and quality of completion on self-selected challenge paths.",
      expected_signal_types: Object.freeze(["completion_quality", "process_efficiency", "execution_accuracy"]),
      scoring_type: "rubric",
      evidence_source: "child_task",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_CQ_03",
      trait_code: "CQ",
      task_class: "OBS",
      prompt: "Observe inquiry behavior during guided science demonstration.",
      instructions:
        "Count meaningful clarifying/extension questions and score whether questions are task-relevant and advance investigation.",
      expected_signal_types: Object.freeze(["behavior_frequency", "observer_rubric_score"]),
      scoring_type: "rubric",
      evidence_source: "assessor_observation",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_CR_01",
      trait_code: "CR",
      task_class: "PRF",
      prompt: "Design three different ways to move a marble across the table using provided materials.",
      instructions:
        "Score originality and usefulness of each design, adherence to safety constraints, and quality of produced artifacts/sketches.",
      expected_signal_types: Object.freeze(["artifact_quality", "completion_quality", "rule_adherence"]),
      scoring_type: "rubric",
      evidence_source: "child_task",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_CR_02",
      trait_code: "CR",
      task_class: "SCT",
      prompt: "Scenario: The school library has a noisy corner problem. Propose multiple workable solutions.",
      instructions:
        "Require at least three distinct options and score option diversity plus justification of practical fit for each option.",
      expected_signal_types: Object.freeze(["option_diversity", "justification_quality", "decision_quality"]),
      scoring_type: "analytic",
      evidence_source: "child_scenario",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_CR_03",
      trait_code: "CR",
      task_class: "RET",
      prompt: "Revise your strongest solution after feedback about feasibility and clarity.",
      instructions:
        "Compare draft 1 and draft 2 for reduced constraint violations, stronger usefulness, and observable strategy shift.",
      expected_signal_types: Object.freeze(["improvement_delta", "strategy_shift_detected", "attempt_quality_change"]),
      scoring_type: "delta",
      evidence_source: "child_retry",
      difficulty_level: "advanced",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_RS_01",
      trait_code: "RS",
      task_class: "SCT",
      prompt: "Scenario: Two students claim different answers to the same riddle. Decide who is correct and explain why.",
      instructions:
        "Score evidence selection, logical consistency, and quality of justification relative to scenario facts.",
      expected_signal_types: Object.freeze(["decision_quality", "justification_quality", "inquiry_depth"]),
      scoring_type: "rubric",
      evidence_source: "child_scenario",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_RS_02",
      trait_code: "RS",
      task_class: "PRF",
      prompt: "Solve a multi-rule sorting challenge where rules change halfway through.",
      instructions:
        "Score rule-transfer accuracy after shift, execution precision, and whether updated logic is applied consistently.",
      expected_signal_types: Object.freeze(["execution_accuracy", "rule_adherence", "process_efficiency"]),
      scoring_type: "analytic",
      evidence_source: "child_task",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_RS_03",
      trait_code: "RS",
      task_class: "OBS",
      prompt: "Observe reasoning talk during peer compare-and-justify activity.",
      instructions:
        "Rate whether claims are backed by relevant evidence, count unsupported assertions, and score coherence of explanation.",
      expected_signal_types: Object.freeze(["observer_rubric_score", "behavior_frequency"]),
      scoring_type: "rubric",
      evidence_source: "teacher_observation",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_PS_01",
      trait_code: "PS",
      task_class: "PRF",
      prompt: "Complete a challenge maze with dead ends while maintaining constructive attempts.",
      instructions:
        "Score continuity of effort after failed paths, quality of successive attempts, and completion under time cap.",
      expected_signal_types: Object.freeze(["completion_quality", "process_efficiency", "execution_accuracy"]),
      scoring_type: "analytic",
      evidence_source: "child_task",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_PS_02",
      trait_code: "PS",
      task_class: "RET",
      prompt: "Retry the maze after brief strategy coaching on checkpointing.",
      instructions:
        "Compare attempt quality, reengagement speed after errors, and error reduction between attempts.",
      expected_signal_types: Object.freeze(["attempt_quality_change", "reengagement_latency", "error_reduction"]),
      scoring_type: "delta",
      evidence_source: "child_retry",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_PS_03",
      trait_code: "PS",
      task_class: "OBS",
      prompt: "Observe persistence markers during a difficult but solvable construction task.",
      instructions:
        "Track constructive reattempt count, abandonment incidents, and whether effort remains goal-directed rather than idle time-on-task.",
      expected_signal_types: Object.freeze(["behavior_frequency", "context_consistency"]),
      scoring_type: "frequency",
      evidence_source: "assessor_observation",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_FB_01",
      trait_code: "FB",
      task_class: "PRF",
      prompt: "Complete a first-pass writing task using a clear rubric.",
      instructions:
        "Capture baseline performance quality and specific rubric misses before feedback is delivered.",
      expected_signal_types: Object.freeze(["completion_quality", "artifact_quality", "rule_adherence"]),
      scoring_type: "rubric",
      evidence_source: "child_task",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: false,
    },
    {
      task_id: "YT_B1_FB_02",
      trait_code: "FB",
      task_class: "RET",
      prompt: "Revise the writing task after receiving two targeted feedback points.",
      instructions:
        "Measure post-feedback improvement delta, explicit correction of flagged errors, and strategy shift in revision behavior.",
      expected_signal_types: Object.freeze(["improvement_delta", "error_reduction", "strategy_shift_detected"]),
      scoring_type: "delta",
      evidence_source: "child_retry",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_FB_03",
      trait_code: "FB",
      task_class: "OBS",
      prompt: "Observe feedback uptake behaviors during revision conference.",
      instructions:
        "Score whether child references feedback points accurately, asks clarification questions, and applies changes without avoidance.",
      expected_signal_types: Object.freeze(["observer_rubric_score", "behavior_frequency", "strategy_use_presence"]),
      scoring_type: "rubric",
      evidence_source: "teacher_observation",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_DE_01",
      trait_code: "DE",
      task_class: "PRF",
      prompt: "Complete a domain-specific mini-project aligned to a chosen interest track.",
      instructions:
        "Score execution quality, artifact quality, and whether project choices reflect continued engagement with the same domain over sessions.",
      expected_signal_types: Object.freeze(["execution_accuracy", "artifact_quality", "completion_quality"]),
      scoring_type: "rubric",
      evidence_source: "child_task",
      difficulty_level: "moderate",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_DE_02",
      trait_code: "DE",
      task_class: "REF",
      prompt: "Reflect on what kept you engaged in this domain and what goal you will pursue next week.",
      instructions:
        "Rate clarity of goal link, strategy awareness, and quality of progress attribution tied to concrete prior work evidence.",
      expected_signal_types: Object.freeze(["goal_link_clarity", "strategy_awareness", "progress_attribution_quality", "domain_commitment_language"]),
      scoring_type: "rubric",
      evidence_source: "assessor_observation",
      difficulty_level: "basic",
      is_repeatable: true,
      is_longitudinal: true,
    },
    {
      task_id: "YT_B1_DE_03",
      trait_code: "DE",
      task_class: "RET",
      prompt: "Re-engage with the same domain project in a later window and improve one self-identified weak component.",
      instructions:
        "Compare windows for attempt quality change, improvement delta, and reduced errors while maintaining domain continuity.",
      expected_signal_types: Object.freeze(["attempt_quality_change", "improvement_delta", "error_reduction"]),
      scoring_type: "delta",
      evidence_source: "child_retry",
      difficulty_level: "advanced",
      is_repeatable: true,
      is_longitudinal: true,
    },
  ]),
});

module.exports = {
  YOUTH_TALENT_BANK_1,
};
